[CmdletBinding()]
param()

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$notesRoot = Join-Path $repositoryRoot 'notes'
$indexPath = Join-Path $repositoryRoot 'INDEX.md'

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Knowledge Base Index')
$lines.Add('')
$lines.Add('> This file is generated by `scripts/update-index.ps1`. Do not edit it directly.')
$lines.Add('')

if (-not (Test-Path -LiteralPath $notesRoot)) {
    $lines.Add('No notes yet. Create one with `scripts/new-note.ps1`.')
}
else {
    $files = Get-ChildItem -LiteralPath $notesRoot -Recurse -File -Filter '*.md' | Sort-Object FullName
    if ($files.Count -eq 0) {
        $lines.Add('No notes yet. Create one with `scripts/new-note.ps1`.')
    }
    else {
        $emittedDirectories = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
        foreach ($file in $files) {
            $relative = $file.FullName.Substring($notesRoot.Length).TrimStart('\', '/')
            $segments = $relative -split '[\\\\/]'
            $directorySegments = @()
            if ($segments.Count -gt 1) {
                $directorySegments = @($segments[0..($segments.Count - 2)])
            }
            for ($index = 0; $index -lt $directorySegments.Count; $index++) {
                $directoryPath = ($directorySegments[0..$index] -join '/')
                if ($emittedDirectories.Add($directoryPath)) {
                    $directoryIndent = '  ' * $index
                    $lines.Add("$directoryIndent- ``$($directorySegments[$index])/``")
                }
            }

            $indent = '  ' * $directorySegments.Count
            $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $firstHeading = Select-String -LiteralPath $file.FullName -Pattern '^#\s+(.+)$' | Select-Object -First 1
            if ($firstHeading) {
                $title = $firstHeading.Matches[0].Groups[1].Value.Trim()
            }
            $link = 'notes/' + ($relative -replace '\\', '/')
            $lines.Add("$indent- [$title]($link)")
        }
    }
}

Set-Content -LiteralPath $indexPath -Value ($lines -join [Environment]::NewLine) -Encoding utf8NoBOM
Write-Output "Updated $indexPath"
